---
# vars file for roles/ansible_azure_create_full_infra
azure_resource_group: openenv-wn2s
azure_pnetwork_name: "{{ azure_resource_group }}-vnet"
azure_pnetwork_cidr: 10.1.0.0/16
azure_pnetwork_subnet_name: "{{ azure_resource_group }}-subnet"
azure_pnetwork_subnet_cidr: 10.1.0.0/24
azure_vm_public_ip: "{{ azure_resource_group }}-pip"
azure_sgroup_name: "{{ azure_resource_group }}-sg"
azure_vm_nic_name: "{{ azure_resource_group }}-{{ azure_vm_instance_name }}-nic"
azure_vm_os_type: linux
azure_vm_admin_username: ansible
azure_vm_instance_name: rhelvm
azure_vm_size: Standard_D4ds_v4
azure_vm_managed_disk_type: Standard_LRS
azure_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDeeXKlbI4ZH7UE8H4QatxnTJjTlCG4u4E/9KpF0zHzpzMZOZyl8A9NK6cNxD3PgqUef+UdKNuTZz+I6TAnPsRpMARYPFt9ipa1E6BAdboYp2CPx2YjasoGHha9V85SlfVDW2RkGi6XxWuNpBTnI1E0c1To6lT3Kojw2QA3oLXDZhiJN7RFv4Q+MzKIoY+K1OB9z3l5dxNoetIU17wrqqOFhnvt5EBqA9GYHZVXEkF2/kzQ6ydIwWwbih9JL5PFsnZsQxTpANLg0+XUAbp5/disNsm6eescI8t2RW0ap+mfVUnc8Y07BIlbocEqaiusVwVcdHJWy0UXdijgS9ssA/ToM4qkTsdaHZDmsmxB1ydYxaWhargnmPWFiihoJFTMJ3xvKGT+U/Ot3c9cwZfhwF6N0FYCfPbr7IuvuVsJL+b7W51CzauOcfvAF7YyVqgwBxDPaKgX6Fifq1wgxZRncdg/+nSXy/rlm5ndzVICTHPsYXabyyvXoWd2czB+u9nu/XE= generated-by-azure"
azure_vm_image_offer: "RHEL"
azure_vm_image_publisher: RedHat
azure_vm_image_sku: '8.1'
azure_vm_image_version: latest



